// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
// import "@hotwired/turbo-rails"
import "vue"
import "jquery"
import "bootstrap"
import "datatables"
import "controllers"
import "common"
import "batches"
import "tranzactions"
import "payments"
import "trial_balance"
